Tests for TitleBar and TimeTimeSeriesSlider components
onaio/gisida-react pull request #186
Opened 2020-03-24 14:45 UTC by ciremusyoka

Part of #185

Adds test for  `lib/components/TimeSeriesSlider` and `lib/components/TitleBar`.

2020-03-24 15:19 UTC, cKellyDesign requested changes
Let's tidy up the tabbing in these files please, they should look as nice in Github as they do in your IDE 💅

2020-03-24 15:19 UTC, cKellyDesign commented on test/lib/components/TimeSeriesSlider/TimeSeriesSlider.test.js
> +}
@ciremusyoka Let's make sure the tabbing in this file is all set to 2 spaces, pls 🙏

2020-03-24 15:19 UTC, cKellyDesign commented on test/lib/components/TitleBar/TitleBar.test.js
> +      <TitleBar  store={store} />
Is there a tab in your component declaration?

2020-03-24 15:25 UTC, moshthepitt requested changes
We should set up [prettier](https://prettier.io/) to deal with things like tabbing for us :)

Setting up prettier with a [husky](https://www.npmjs.com/package/husky) pre-commit hook takes about 15 minutes, and we can just copy the config from [other](https://github.com/onaio/reveal-frontend) [projects](https://github.com/onaio/grp-frontend) [that](https://github.com/onaio/kaznet-frontend) [have](https://github.com/onaio/js-tools) [this](https://github.com/opensrp/opensrp-web).

@cKellyDesign @ciremusyoka @kahummer ^^

2020-03-24 15:32 UTC, ciremusyoka commented
@moshthepitt  i will add `prettier`.

2020-04-21 18:49 UTC, cKellyDesign commented
@ciremusyoka what's the status of this PR?

2021-09-29 08:39 UTC, closed without merging